# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKj3PLjvvY4dRSU0kJVtNt07e5fuzeDw
"""

!pip install streamlit

# Ensure streamlit is installed
!pip install streamlit

import streamlit as st
import pandas as pd
import joblib  # For saving and loading the model
from sklearn.linear_model import LinearRegression

# Load your trained model (assume you saved it as model.pkl)
model = joblib.load('/content/Final_scorepickle.pkl')

# Title
st.title("🎓 Student Final Score Predictor")

# Input fields
study_hours = st.slider("📚 Daily Hours of Study", 0, 15, 2)
mobile_usage = st.slider("📱 Mobile Usage While Studying (in hours)", 0, 10, 1)
sleep_hours = st.slider("😴 Sleep Hours Before Exam", 0, 12, 6)
attendance = st.text_input("📅 Attendance Percentage (e.g., 85%)", "90%")
doubt_session = st.selectbox("❓ Participation in Doubt Sessions", ["Yes", "No"])

# Preprocessing
if '%' in attendance:
    attendance = attendance.replace('%', '')
attendance = float(attendance)

# Encode doubt session
doubt_session_encoded = 1 if doubt_session == "Yes" else 0

# Prediction
if st.button("Predict Final Score"):
    input_df = pd.DataFrame([[study_hours, mobile_usage, sleep_hours, attendance, doubt_session_encoded]],
                            columns=['What is the dialy hours of study?',
                                     'Usage of mobile phone while studying',
                                     'Sleep Hours before exam?',
                                     'Percentage of Attendance',
                                     'Participation in doubt sessions'])

    prediction = model.predict(input_df)[0]
    st.success(f"🎯 Predicted Final Score: {prediction:.2f}")